name: uraba
description: "Plataforma Digital para Comerciantes de Uraba."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- BLOQUE DE FIREBASE ACTUALIZADO (Compatible con Pigeon) ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0

  # --- DISEÑO Y GOOGLE ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2  # Esta versión funciona perfecto con Auth ^5.3.1

  # --- CONECTIVIDAD ---
  connectivity_plus: ^5.0.0
  # --- ANIMACIONES ---
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_bg.jpg
    - assets/images/register_bg.jpg